### ISSUE TITLE
Instead of using  stixtransclient.py - use the direct STIX import of MISP (you are loosing a lot of data with the current scheme)

### ISSUE THREAD

**Issue by adulau** [cisagov/flare-misp-service#3]
# 🚀 Feature Proposal

Instead of using  stixtransclient.py - use the direct STIX import of MISP (you are loosing a lot of data with the current scheme)

## Motivation

you are loosing a lot of data with the current scheme and you get the full complete STIX into MISP.

## Example

There is an entry point in the API in MISP to directly ingest STIX files (and the parsing is done on MISP side).

## Pitch

- It will simplify the code base (CTI toolkit is not required anymore)
- Full STIX events with all relationship and objects are imported in MISP
- Allowing CISA MISP users to fully get all the data shared by CISA 

## How to implement

- At https://github.com/cisagov/flare-misp-service/blob/master/misp-trans-client-rest-service/src/main/java/org/gd/ddcs/flare/misp/MispTransClientController.java#L339 - a simple step can be added to push the XML into MISP directly.
- We can also create a sample Python script to show you how to do it.

**Comment by adulau** [comment]
To simply the process, we create a direct Python ingest script for STIX 1 or STIX 2 files in MISP:

- https://github.com/MISP/MISP/tree/2.4/tools/ingest_stix 

This can be easily use to replace the old script from the CTI toolkit.

**Comment by drkiettran** [comment]
CISA/CTM: The latest code from this repository is no longer using CTI toolkit but relies on the MISP Server for the transformation.

This issue is now closed.
