### ISSUE TITLE
Configuration Instructions Edits

### ISSUE THREAD

**Issue by blu3gl0w13** [cisagov/flare-misp-service#8]
# 💡 Summary #

What is the work, as a high-level summary?
Just curious about step 6 in the instructions  as it's unclear what goes into the 'stixtransclient.misp.key' parameter within the config.properties file. Is this an auth key from MISP that is being encrypted, is this an encrypted user password for accessing the MISP server. Any clarification you can provide would be helpful. I'm trying to follow your instructions and up until step 6, they have been crystal clear. If there's a better place to pose this request/question, I'm happy to go through those means but didn't find a way to solve my own problem after extensive research in both this README and the MISP API documentation.

**Comment by drkiettran** [comment]
We are pushing a fix out shortly. Thank you for your comment. It was very helpful.
